# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time
from PyQt5.QtWidgets import QApplication

f = open('GUI/outfile.txt', 'r')
gl_time = 1

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(40, 10, 371, 61))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.title_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.title_label_2.setGeometry(QtCore.QRect(580, 30, 91, 28))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.title_label_2.setFont(font)
        self.title_label_2.setObjectName("title_label_2")
        self.time_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.time_lcd.setGeometry(QtCore.QRect(687, 20, 91, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_lcd.sizePolicy().hasHeightForWidth())
        self.time_lcd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.time_lcd.setFont(font)
        self.time_lcd.setObjectName("time_lcd")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(681, 476, 101, 62))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.next_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.next_button.setFont(font)
        self.next_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_button.setObjectName("next_button")
        self.verticalLayout.addWidget(self.next_button)
        self.auto_button = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.auto_button.setFont(font)
        self.auto_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.auto_button.setMouseTracking(True)
        self.auto_button.setObjectName("auto_button")
        self.verticalLayout.addWidget(self.auto_button)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(561, 100, 221, 191))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.stations_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.stations_label.setFont(font)
        self.stations_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stations_label.setAutoFillBackground(False)
        self.stations_label.setObjectName("stations_label")
        self.gridLayout.addWidget(self.stations_label, 2, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.distance_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.distance_label.setFont(font)
        self.distance_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.distance_label.setAutoFillBackground(False)
        self.distance_label.setObjectName("distance_label")
        self.gridLayout.addWidget(self.distance_label, 3, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.stratedy_lable = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.stratedy_lable.setFont(font)
        self.stratedy_lable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stratedy_lable.setAutoFillBackground(False)
        self.stratedy_lable.setObjectName("stratedy_lable")
        self.gridLayout.addWidget(self.stratedy_lable, 4, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.status_label = QtWidgets.QLabel(self.widget)
        self.status_label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.status_label.setFont(font)
        self.status_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.status_label.setAutoFillBackground(False)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 0, 1, 1, 2)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(560, 310, 221, 71))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.exp_label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.exp_label.setFont(font)
        self.exp_label.setObjectName("exp_label")
        self.gridLayout_2.addWidget(self.exp_label, 0, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.widget1)
        # self.progressBar.maximum()
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 2)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(90, 180, 241, 201))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.widget2.setFont(font)
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "公交车调度系统动画演示界面（测试）"))
        self.title_label_2.setText(_translate("MainWindow", "运行时间："))
        self.next_button.setText(_translate("MainWindow", "NEXT"))
        self.auto_button.setText(_translate("MainWindow", "AutoRun"))
        self.label_3.setText(_translate("MainWindow", "当前配置文件"))
        self.label_4.setText(_translate("MainWindow", "总车站数："))
        self.stations_label.setText(_translate("MainWindow", "——"))
        self.label_6.setText(_translate("MainWindow", "车站间距："))
        self.distance_label.setText(_translate("MainWindow", "——"))
        self.label_8.setText(_translate("MainWindow", "调度策略："))
        self.stratedy_lable.setText(_translate("MainWindow", "——"))
        self.label.setText(_translate("MainWindow", "运行状态："))
        self.status_label.setText(_translate("MainWindow", "运行/停运"))
        self.label_10.setText(_translate("MainWindow", "预计运行时间"))
        self.exp_label.setText(_translate("MainWindow", "--"))
        self.label_13.setText(_translate("MainWindow", "TEMP_comand_display"))
        self.label_15.setText(_translate("MainWindow", "——"))
        self.label_12.setText(_translate("MainWindow", "TEMP_position_display"))
        self.label_14.setText(_translate("MainWindow", "——"))

        # signals:
        self.next_button.clicked.connect(self.read_file)
        self.auto_button.clicked.connect(self.autoplay)

    # 读输出文件（outfile.txt）,解析，发送信号
    def read_file(self):
        global f

        raw_time = f.readline()
        # 判断进程结束（有bug）
        if raw_time == EOFError:
            self.next_button.disconnect()
            self.auto_button.disconnect()
        raw_time = raw_time.split(':')[1]

        # 更新运行时间
        self.time_show(raw_time)
        # 更新进度条
        self.display_progressbar(value=int(raw_time))

        # 更新车辆位置
        raw_pos = f.readline()
        raw_pos = raw_pos.split(':')[1]
        self.test_postionshow(raw_pos)

        # 更新当前指令
        raw_cmd = f.readline()
        raw_cmd = raw_cmd.split(':')[1]
        self.test_cmdshow(raw_cmd)

    # 自动播放选项
    def autoplay(self):
        suspend_sec = 0.5
        while self.auto_button.isChecked():
            self.next_button.click()
            QApplication.processEvents()
            time.sleep(suspend_sec)

    # 绘制路线图背景（暂无）
    def backdraw(self):
        pass

    # 显示配置文件
    def config(self, strategy, stations, distance):
        self.stratedy_lable.setText(strategy)
        self.stations_label.setText(stations)
        self.distance_label.setText(distance)

    # 显示运行时间
    def time_show(self, time):
        self.time_lcd.display(time)

    # 显示总（预期）时间
    def set_GT(self, GT):
        global gl_time
        gl_time = GT
        self.exp_label.setText(GT)

    # 显示位置（临时）
    def test_postionshow(self, pos):
        self.label_14.setText(pos)

    # 显示指令（临时）
    def test_cmdshow(self, cmd):
        self.label_15.setText(cmd)

    # 设定进度条最大值（总时间）
    def set_progressbar(self, value):
        self.progressBar.setMaximum(value)

    # 更新进度条
    def display_progressbar(self, value):
        self.progressBar.setValue(value)
